### ISSUE TITLE
Error while invoking Upload Init API

### ISSUE THREAD

**Issue by thiru2496** [Bynder/bynder-c-sharp-sdk#10]
[bynder-c-sharp-sdk-master.zip](https://github.com/Bynder/bynder-c-sharp-sdk/files/2500045/bynder-c-sharp-sdk-master.zip)

Hi Team,
As discussed in the call, we are posting the source code after removing the token secrets and Customer key/secret is there in the app.config file. We attached the error which are getting while invoking  Upload API. In addition to this error, we are getting another error "IOException:The handshake failed due to an unexpected pocket format."

![error](https://user-images.githubusercontent.com/42100489/47276065-9958d280-d582-11e8-8328-24bdaffdf09e.JPG)

**Comment by danielsequeira** [comment]
Hi @thiru2496! We just tested uploading a file to Bynder using the SDK and with the same tokens and it worked. Did you change any code in the ApiSample.cs file?
Also are you getting the token and token secret through the browser authentication?
