### ISSUE TITLE
Is it possible to use the api in a windows service?

### ISSUE THREAD

**Issue by bermogalan** [Bynder/bynder-c-sharp-sdk#16]
HI, 

I want to use your sdk for my windows service. Do you have a sample code for getting authorization without launching the browser?

Thanks

**Comment by danielsequeira** [comment]
Hi @bermogalan,

You can use the SDK without launching the browser, but for that you need to have a the following API tokens: `CONSUMER_KEY`. `CONSUMER_SECRET`, `TOKEN` and `TOKEN_SECRET` for you Bynder account and instantiate the SDK using those values as settings: https://github.com/Bynder/bynder-c-sharp-sdk/blob/master/Bynder/Api/Impl/BynderAPI.cs#L63
