### ISSUE TITLE
Error while installing nuget package

### ISSUE THREAD

**Issue by mahesh-newale** [Bynder/bynder-c-sharp-sdk#17]
Hi Team,
I am trying to install the NuGet package in my .Net console application (.Net Framework 4.5.2) but I am getting below error. 
Could not install package 'Bynder.Sdk 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is there any other type of project require. I want it as a console application, so i can create a scheduler for it.

**Comment by danielsequeira** [comment]
Hi,

Would it be possible for you to upgrade to `.Net Framework 4.6.1`?

The other solution would be for us to downgrade our SDK library from `.NETStandard 2.0` to `.NETStandard 1.2`.

**Comment by mahesh-newale** [comment]
I tried with .Net Framework 4.6.1 but no luck. I got Same issue as before. 
So I tried with .NETStandard 1.2.2 and its work.
hope there is no much difference between 1.2.2 and 2.0.

**Comment by danielsequeira** [comment]
Cool, I will have a look and make some tests and if possible, release a new version of the SDK that is compatible with `.Net Framework 4.5.2`

**Comment by mahesh-newale** [comment]
Is this sdk only support OAuth 2.0 for authentication?

**Comment by danielsequeira** [comment]
yes, the last version of the SDK only supports OAuth 2.0

**Comment by TClemonsOC** [comment]
Any chance of getting a release for .net 4.7.x

**Comment by githuib** [comment]
> Any chance of getting a release for .net 4.7.x

In our latest release, .NET standard is set to 2.0, which supports framework 4.7.x

For a more complete overview of what it supports: https://dotnet.microsoft.com/platform/dotnet-standard#versions
