### ISSUE TITLE
Ability to Add Thumbnail Image

### ISSUE THREAD

**Issue by greenrya** [Bynder/bynder-c-sharp-sdk#25]
We have a need in our API to add a different thumbnail image to a asset.  It would be great if the API could be enhanced to allow for that.

**Comment by TimBloembergen** [comment]
Hi @greenrya, Sorry for the late reply on this one. This functionality does not exist within Bynder therefor it isn't possible to achieve this via the API either. When or if this logic will be build we will do our best to get this functionality within the SDK as well.
