### ISSUE TITLE
Ability to Relate Assets through the API

### ISSUE THREAD

**Issue by greenrya** [Bynder/bynder-c-sharp-sdk#26]
We are uploading a grouping of assets and want the ability to "Relate" them using the SDK is this possible it does not appear to be.

**Comment by githuib** [comment]
I'm not sure what you mean exactly by "relating" here in the context of Bynder. But it's possible to add assets to a collection, with `CollectionService.AddMediaAsync()` for example, or you could use `AssetService.ModifyMediaAsync()` to give the asset certain metaproperty options.

I hope this helps,
Huib
