### ISSUE TITLE
IAssetService.GetMediaListAsync() - filtering by PropertyOptionId does not seem to work.

### ISSUE THREAD

**Issue by awcoats** [Bynder/bynder-c-sharp-sdk#28]
I'm using the following code to try and query Bynder
``` 
var mediaList = assetService.GetMediaListAsync(new MediaQuery()
{                        
    BrandId = brandID,                   
    Page = page,
    PropertyOptionId= new List<string>() { "788FBBCC-F382-4E26-982C4CD0FEA7FD07"},
    Limit = 1000
}).Result;
```

The PropertyOptionId does not seem to influence the number of returned items. If I change the GUID to anything, I still get the same number of results returned.

I would expected an empty list to be returned if I used the following:
```
PropertyOptionId= new List<string>() { "blah"},
```

I'm obtaining the  OptionID  from calling `assetService.GetMetapropertiesAsync()`

**Comment by githuib** [comment]
Does `"788FBBCC-F382-4E26-982C4CD0FEA7FD07"` represent an ID of an existing metaproperty option ID here? I couldn't reproduce it in that case.

The behavior of ignoring non-existing IDs (such as "blah") is just how the API currently is working. I can see if we would want to change that, but it's not something we can change in this SDK.
