### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by bweber** [Bynder/bynder-c-sharp-sdk#3]
Using the SDK to test making calls to the API. Getting Invalid signature using the sample client against our API. Used this site (http://lti.tools/oauth/) to verify the signature and it matches what is generated by the client. Not sure if client is incorrect or the API is.

**Comment by radoslav-h-todorov** [comment]
Try to change your `API_BASE_URL` from `https://plugin.getbynder.com/` with `https://<your_tenant_id>.bynder.com/` 

I had the same error and after I did the change is stopped to see the error.

**Comment by danielsequeira** [comment]
Yes, you will need to set up your account base URL and OAuth1 tokens in the bynder-c-sharp-sdk/Bynder/Sample/App.config file, before running the sample.

**Comment by condemil** [comment]
@bweber is the answers above resolved your issue?

**Comment by cindy-ho** [comment]
Is the BASE URL https://www.domain.com or https://www.domain.com/, with the slash appended?

**Comment by cindy-ho** [comment]
Sorry just realized a slash is needed, scratch my question.

**Comment by danielsequeira** [comment]
@bweber do you still need help regarding this?
