### ISSUE TITLE
Allow additional handlers in chain

### ISSUE THREAD

**Issue by gobsmack** [Bynder/bynder-c-sharp-sdk#4]
I have a requirement to inject additional DelegatingHandlers into the request chain when calling Bynder. For example, I use a handler that logs all requests and responses. Or, one may choose to enrich the HttpClientHandler with corporate proxy settings.

Currently, I'm accomplishing this by modifying internal code deep within the SDK. I would prefer not to fork the SDK.

Would you welcome a PR that introduced an override to the BynderApiFactory, allowing the developer to pass in a handler chain?

**Comment by JoanM** [comment]
Sure, it is something that it makes sense to be able to inject. So, if you have it ready you can create a PR for it.

**Comment by danielsequeira** [comment]
@gobsmack there's anything else you need regarding this issue? If not I will close it and we will wait for your pull request regarding this.
