### ISSUE TITLE
Error in retrieving Media on activeOriginalFocusPoint as int, but gets a decimal

### ISSUE THREAD

**Issue by meghuizen** [Bynder/bynder-c-sharp-sdk#48]
I'm proposing that the structure of Media.ActiveOriginalFocusPoint get changed, where it doesn't expect an int, but a decimal.
https://github.com/Bynder/bynder-c-sharp-sdk/blob/6261c418661789f958501f36733c1f479225f674/Bynder/Sdk/Model/Media.cs#L33

This is the error I get:

> **Newtonsoft.Json.JsonReaderException**: 'Input string '268.5' is not a valid integer. Path 'activeOriginalFocusPoint.y', line 1, position 2591.'

![image](https://user-images.githubusercontent.com/367462/108068703-b9b9ce80-7062-11eb-8671-be7c271046f9.png)

It tries to fit a decimal value inside an int, which doesn't work.
If you change the datatype from int to decimal, that should fix the problem.

Kind regards,

Michiel

**Comment by githuib** [comment]
Thanks for mentioning this issue. I've added a fix for it to the upcoming release (2.2.4).
