### ISSUE TITLE
Passing metaproperties on new asset upload / add later

### ISSUE THREAD

**Issue by heliorvath** [Bynder/bynder-c-sharp-sdk#51]
Hi!

I'm trying to automate bulk uploading of documents to Bynder. I got around to uploading the files themselves, and there is never an issue with a new version for assets with the metaproperties already given.
However, when I'm uploading a new asset/media, I need to be able to pass some properties (i.e. job number, visibility, asset-type, etc...) along with the upload.
I don't think there is a method for this with this SDK, and I'm struggling to figure out, which class and how to alter, to be able to pass the required data.
I'm also not sure whether to approach this issue from uploading with the properties to begin with, or once uploaded, find the match in the medialist through the (default name = filename), and passing/filling the dictionary with the needed data.

I can retrieve these from existing media with (once I have a list of media) media.PropertyOptionsDictionary[] and specifying the name (e.g. "property_job_number") of the value I'm looking for.

**Comment by githuib** [comment]
> I need to be able to pass some properties (i.e. job number, visibility, asset-type, etc...) along with the upload.

Just to be sure, do you mean these properties are metaproperties (or more precisely metaproperty options)? There are methods to achieve this in the Bynder API, but unfortunately they are not implemented in the C# SDK.

**Comment by heliorvath** [comment]
Metaproperty options yes. If I were to get them from a media that's already up, I would have to use the for example: media.PropertyOptionsDictionary["property_job_number"]. I just need to find a way to pass some of these with the upload.

**Comment by githuib** [comment]
With our API that would be possible in two ways:
During upload (using the `metaproperty` attribute): https://bynder.docs.apiary.io/#reference/upload-assets/4-finalise-a-completely-uploaded-file/save-as-a-new-asset
By modifying an asset (using the `metaproperty.ID
` attribute): https://bynder.docs.apiary.io/#reference/assets/specific-asset-operations/modify-asset

But unfortunately, there is no way to pass those attributes using the C# SDK.

**Comment by githuib** [comment]
Closing this issue, as functionality to pass metaproperty options in the save & modify media requests will be available in version 2.2.10 of the SDK (that should appear on NuGet any time soon).
