### ISSUE TITLE
OAuth setup with relative urls breaks with Tridion integration (SDK v1.2.2)

### ISSUE THREAD

**Issue by kunalshetye** [Bynder/bynder-c-sharp-sdk#56]
Example Configuration:
<EnvironmentUrl xmlns="ecl:BynderProvider">https://internal-api-gateway/bynder/</EnvironmentUrl>

Expected API Call	: https://internal-api-gateway/bynder/api/media
Actual API Call		: https://internal-api-gateway/api/media

Notice that the **/bynder** gets stripped out because of how Uri's in C# are combined.

The code change required for this bugfix can be found here: https://github.com/kunalshetye/bynder-c-sharp-sdk/commit/c3678499330b8eb2070d9fec9c583bd5bc4e648d

Unfortunately it's not possible for me to open a Pull Request since the Master Branch is way ahead of SDK v1.2.2

**Comment by githuib** [comment]
Hello @kunalshetye 

In more recent versions, we build up URIs with the built in `UriBuilder`, which already takes care of this.

We'll only make fixes or other changes to the latest version. I do wonder if there is any specific reason you are using this particular version of the SDK? In case you would like to upgrade, or for any reason struggle to do so, please let me know so I can see if we can help out with that.

**Comment by kunalshetye** [comment]
Hi, the Tridion Bynder integration provided by Bynder uses an older version of the SDK v1.2.2 hence the issue was raised on an older version. Would it be possible to upgrade the integration to the latest version of the SDK? That would automatically resolve the issue

**Comment by kunalshetye** [comment]
With the latest version of the Integration (v2.0.0) which uses the latest SDK (v2.2.7) this issue is now resolved
