### ISSUE TITLE
ActiveOriginalFocusPoint issue. Exception being thrown when Media is deserialized

### ISSUE THREAD

**Issue by Yosif-Smint** [Bynder/bynder-c-sharp-sdk#75]
Hello,

The issue that we are facing is that when we request 'Media' data via the SDK, we get an exception being thrown.
Thus this requires us to fork the repository.

The exception for a refence is
```
Newtonsoft.Json.JsonReaderException: 'Input string '266.5' is not a valid integer. Path 'activeOriginalFocusPoint.y', line 1, position 4425.'
```
This is due to the property defined in the Media.cs file. 
```
/// <summary>
/// Active focus point in the original media item, defined
/// by an x,y coordinate.
/// </summary>
[JsonProperty("activeOriginalFocusPoint")]
public IDictionary<string, int> ActiveOriginalFocusPoint { get; set; }
```
The data type has a mismatch and Newtonsoft is complaining about it when it deserializes the object by throwing the exception.

Since this deserialization is done in the 'ApiRequestSender.SendRequestAsync()' method, we can not pass 'JsonSerializerSettings', so we can not override this behavior. 

I understand that an existing Tier-1 client is having difficulties this being 'double' or 'float'.

There a bunch of ways to skin a cat. 
Lets discuss how we will deal with this one.

Yosif

**Comment by Arpit-Sharma-USC** [comment]
Hey @Yosif-Smint. Thanks for isolating this in a separate issue. The focus points refer to pixels so they should never be floats/double with decimal places. So I would say this would be a bug in the response. Can you please contact the support and create a ticket with them? This will ensure the bug reaches the proper team and an appropriate procedure is followed on its way to a resolution. It will also help you stay updated about the progress on this bug resolution via the Bynder support.

Thanks!

**Comment by Yosif-Smint** [comment]
Perfect.
I will create the ticket and will keep you posted on this thread.
Thanks @Arpit-Sharma-USC

**Comment by Yosif-Smint** [comment]
As per the discussion with the support. They are investigating how I was able to upload assets with the ActiveOriginalFocusPoint being double.

There is a short term fix if someone is interested or in this situation.
```
Our UI prevents using decimals when setting the focus point which matches what the SDK behavior is using Int versus Double.
One solution, while we wait to hear back, is to resave the asset to remove the decimal formatting. 
```

**Comment by Reonekot** [comment]
Thanks for the update - I don't think the workaround is that easy in practice for us, as the ones using "our custom display of assets" are external users around the world, so we can't expect them to report back when an asset doesn't load. It's ofc. a possibility to setup logging on the server-side and follow up, but from my short testing it is many of our assets that doesn't load due this.

Let me know if you/support need details on another case/account.

**Comment by Yosif-Smint** [comment]
I have not received a response from the support team since what I posted.
I will let you know if things change.
I would love if they fix this.
Nothing we can do unless to escalate it as an issue :)

**Comment by Yosif-Smint** [comment]
According to Bynder, this issue should be no more.
