### ISSUE TITLE
Missing LinkedOptionIds property on the model

### ISSUE THREAD

**Issue by kunalshetye** [Bynder/bynder-c-sharp-sdk#8]
The MetapropertyOption model does not expose the linkedOptionIds. I've submitted a pull request with an update to the model here: [https://github.com/Bynder/bynder-c-sharp-sdk/pull/7](https://github.com/Bynder/bynder-c-sharp-sdk/pull/7)

**Comment by MartenSies** [comment]
Thanks, I've merged your pull request.
