### ISSUE TITLE
How to find specific asset via metadata

### ISSUE THREAD

**Issue by ghost** [Bynder/bynder-c-sharp-sdk#85]
Hi
Just getting started with an integration to Bynder.
I am using the SDK for C# and have gotten it up and running.
The application we are developing should find an asset (image)
by metadata associated to a particular image – that is the goal at least.

What I can read from the api documentation, is that I could use “property_NAME” to find my asset.
But in the SDK there is no such property in the “MediaQuery” class for C#.

How would I find an image via the SDK in my case? Perhaps I have missed something?

Best regards
/Peraxel, Zitac Solutions (Bynder partner)
peraxel.mars@zitacsolutions.se

**Comment by TimBloembergen** [comment]
Hi @PeraxelZitac,

You are right in saying that the parameter `property_NAME` is not implemented in the C# SDK. There are currently no plans in making changes to the SDKs. 
However, the SDK projects are opensource and we like to encourage users of them to make PRs if there are feature requests or if bugs need to be resolved as soon as possible.

In this case feel free to create a PR to add the missing parameter. Our team will review and merge if the code changes meet our standards.

Kind regards, Tim
