### ISSUE TITLE
MediaQuery in API

### ISSUE THREAD

**Issue by Alfetta159** [Bynder/bynder-c-sharp-sdk#86]
How does one add filters to their MediaQuery object? I want an analogy to the following query:

`GET: https://domain.com/api/v4/media?limit=100&page=1&property_Channel=Digital&property_ChannelSubType=Salsify&property_UsageRights=Active`

This doesn't seem to work. It doesn't give me a BadRequest either.

```C#
new MediaQuery
        {
            Limit = 100,
            Page = 1,
            PropertyOptionId = new List<string>
                {
                    "property_UsageRights:Active",
                    "property_Channel:Digital",
                    "property_ChannelSubType:Salsify",
                    "property_UsageRights:Active"
                }
        };
```

Pro tip: If `PropertyOptionsId` represents a collection, then it should probably have a pluralized name.

**Comment by Alfetta159** [comment]
I tried a couple more schemes for the `PropertyOptionId` property to no avail. I even tried calling resulting URLs generated by the SDK. Neither of these work.

> If the `PropertyOptionId` property is not supported, perhaps it should throw a `NotSupported` exception(?)

`https://domain/api/v4/media?limit=500&page=1&propertyOptionId=property_UsageRights=Active,property_Channel=Digital,property_ChannelSubType=Salsify,property_UsageRights=Active`

`https://domain/api/v4/media?limit=500&page=1&propertyOptionId=property_UsageRights:Active,property_Channel:Digital,property_ChannelSubType:Salsify,property_UsageRights:Active`

**Comment by TimBloembergen** [comment]
Hi @Alfetta159 , I've had a look and unfortunately the `property_NAME` parameter is currently not supported in the C# SDK. The supported parameters can be found in this file https://github.com/Bynder/bynder-c-sharp-sdk/blob/master/Bynder/Sdk/Query/Asset/MediaQuery.cs

We currently do not have the people available to implement new features in the C# SDK. But feel free to create a PR with the required changes and we will look into it. If the code changes meet our standards we will be able to make a new release.

**Comment by Alfetta159** [comment]
Can you tell me the general syntax for querying more than one property_Channel if that is possible?

e.g. `property_Channel=Digital,Salsify` or `property_Channel=(Digital or Salsify)`

I do realize this is not a question about this SDK/repo, but the documentation on the [Bynder website](https://developer-docs.bynder.com/api/searching-and-filtering-assets) is limited, there doesn't seem to be a Bynder community forum, and there isn't a lot of discussion on sites like [StackOverflow](https://stackoverflow.com/search?q=Bynder+API).

**Comment by TimBloembergen** [comment]
Hi @Alfetta159 , I just ran some quick tests and if you'd want to query for multiple values for the same metaproperty you'd have to use `optionIds` instead. The actual complete API docs can ben found [here](https://bynder.docs.apiary.io/#introduction/welcome-to-the-bynder-api-documentation)

Hope this helps!
